name: Tests

on:
  push:
    paths:
      - "src/**"
    branches:
      - 1.x

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 🔨 setup node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: 🔨 install Yarn and dependecies
        run: |
          npm install -g yarn
          yarn install
          
      - name: Run jest
        run: yarn run test

      - name: 🔨 uninstall Yarn
        if: always()
        run: npm uninstall -g yarn